services:
  verdaccio:
    container_name: verdaccio
    image: verdaccio/verdaccio:latest
    ports:
      - '4873:4873'
    volumes:
      - './conf:/verdaccio/conf'
      - './storage:/verdaccio/storage'

volumes:
  verdaccio:
    driver: local