storage: /verdaccio/storage

auth:
  htpasswd:
    file: /verdaccio/conf/htpasswd

security:
  api:
    jwt:
      sign:
        expiresIn: 60d
        notBefore: 1

web:
  title: Verdaccio
  sign:
    expiresIn: 7d

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  "@*/*":
    access: $all
    publish: $all
    proxy: npmjs
  "**":
    access: $all
    publish: $all
    proxy: npmjs

middlewares:
  audit:
    enabled: true

logs:
  - { type: stdout, format: pretty, level: trace }
